name: Mineframe
version: '${version}'
main: me.abdullahrasheed.mineframe.MineframePlugin
description: A PaperMC plugin.
author: Abdullah Rasheed
api-version: '26.2'
commands:
  materials:
    description: Opens your FrameMaterial collection.
    usage: /materials [reload]
    permission: mineframe.command.materials
permissions:
  mineframe.command.materials:
    description: Allows a player to open the materials menu.
    default: true
  mineframe.command.materials.reload:
    description: Allows reloading material-drops.yml.
    default: op
